PORT=8000
MONGODB_URI=mongodb+srv://hasanerol7205:cTX86ZyIUm1hT3BF@cluster0.pbgzd.mongodb.net/mernstore2?retryWrites=true&w=majority&appName=Cluster0
REDIS_URL=rediss://default:AdZ1AAIjcDFlYjY2Mjg0YmY5Mjk0NWFmYThkNzUzZjZiYzYxYjk1OXAxMA@grown-newt-54901.upstash.io:6379
ACCESS_TOKEN_SECRET=access_token_secret
REFRESH_TOKEN_SECRET=refresh_token_secret